# Generated by Django 4.2 on 2023-04-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("words", models.JSONField()),
                ("cache", models.JSONField()),
                ("threshold", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
